name: MenuCraft CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Instalar dependencias del Frontend
      run: |
        if [ -d "frontend" ]; then
          npm install --prefix frontend
        else
          echo "La carpeta frontend aun no existe, omitiendo temporalmente."
        fi
